version: 0.0
os: linux
files:
- source: target/spring-app.jar
  destination: /home/ec2-user/javaapp
hooks:
  AfterInstall:
  - location: scripts/install_java
    timeout: 300
    runas: root
  ApplicationStart:
  - location: scripts/start_server
    timeout: 300
    runas: root
  ApplicationStop:
  - location: scripts/stop_server
    timeout: 300
    runas: root

