AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack for creating sertifiseringer webpage
Parameters:
  Prefix:
    Type: String
    Default: eira-testt
Resources:
  LambdaUploadToS3SAM:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: s3://eira-test-sam-deployment/db22ce26d841a9f94a6fa5481701ea4f
      MemorySize: 128
      Timeout: 10
      Events:
        UploadEvent:
          Type: HttpApi
          Properties:
            Path: /upload
            Method: PUT
            ApiId:
              Ref: MyHttpApi
  LambdaToDynamoDBSAM:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: s3://eira-test-sam-deployment/30dcc2ba9f3e1b5fd13bbb7ac411dd4c
      MemorySize: 128
      Timeout: 10
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            Path: /sertifiseringer
            Method: GET
            ApiId:
              Ref: MyHttpApi
        GetIdEvent:
          Type: HttpApi
          Properties:
            Path: /sertifiseringer/{id}
            Method: GET
            ApiId:
              Ref: MyHttpApi
        PutEvent:
          Type: HttpApi
          Properties:
            Path: /sertifiseringer
            Method: PUT
            ApiId:
              Ref: MyHttpApi
        DeleteEvent:
          Type: HttpApi
          Properties:
            Path: /sertifiseringer/{id}
            Method: DELETE
            ApiId:
              Ref: MyHttpApi
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Fn::Join:
            - ''
            - - Ref: Prefix
              - -sam-sertifiseringer-table
  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
      CorsConfiguration:
        AllowOrigins:
        - '*'
        AllowHeaders:
        - '*'
        AllowMethods:
        - '*'
  BucketPolicySAM:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action:
          - s3:*
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: MyS3BucketSAM
              - /*
      Bucket:
        Ref: MyS3BucketSAM
  MyS3BucketSAM:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName:
        Fn::Join:
        - ''
        - - Ref: Prefix
          - -sam-sertifiseringer-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
  MyDynamoDBTableSAM:
    Type: AWS::Serverless::SimpleTable
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      PrimaryKey:
        Name: id
        Type: String
      TableName:
        Fn::Join:
        - ''
        - - Ref: Prefix
          - -sam-sertifiseringer-table
